############################
### DurabilityCustomizer ###
############################

##################################
###         DURABILITY         ###
### -------------------------- ###
### Toggles global durability. ###
##################################

# values: [disabled, enabled]
# - `disabled` means that the minecraft feature is disabled.
# - `enabled` enables it.

durability:
  item-durability: disabled
  anvil-damage: disabled

##########################################
###              OVERRIDES             ###
### ---------------------------------- ###
### Tool-personal durability settings. ###
##########################################

# the override key is an item ID.
# the value is the value each damage taken is multiplied by.
#       (if it's 0, there's inf durability)

overrides:
  diamond_pickaxe: 0

#########################################################
###                      UNSAFE                       ###
### ------------------------------------------------- ###
### Settings that may potentially damage your server. ###
#########################################################

unsafe:
  # This is a special tag useful for when you've set up your server to use the unbreakable tag,
  # but messed it up at some part.
  #
  # For example:
  # > **Problem:**
  #   The shopkeepers have all cost items with unbreakability,
  #   but output breakable items.
  #
  #   **Solution:**
  #   Set `enabled` to true,
  #       `value`   to true.
  #
  # > **Problem:**
  #   The shopkeepers have all items without unbreakability,
  #   so you've installed another plugin to make all items unbreakable.
  #
  #   The plugin that was supposed to fix the issue made it even worse,
  #   as it added the Unbreakable:1b tag, which wasn't described anywhere.
  #
  #   **Solution:**
  #   Set `enabled` to true,
  #       `value`   to false.
  #
  force-unbreakable-tag:
    enabled: false
    value: true
